# Generated by Django 3.2.8 on 2021-11-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211028_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title_tag',
            field=models.CharField(default='Title', max_length=150),
        ),
    ]
